src/Entity/Apotheose.php
<?php

namespace App\Entity;

use App\Repository\ApotheoseRepository;
use App\Repository\UrlApotheoseRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ApotheoseRepository::class)
 */
class Apotheose
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $promo;

    /**
     * @ORM\Column(type="text")
     */
    private $description;



    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_publish;

    /**
     * @ORM\OneToMany(targetEntity=UrlApotheose::class, mappedBy="apotheose")
     */
    private $urlapotheose;

    public function __construct()
    {
         $this->createdAt= new DateTime();
        $this->is_publish= false;
        $this->urlapotheose = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPromo(): ?string
    {
        return $this->promo;
    }

    public function setPromo(string $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIsPublish(): ?bool
    {
        return $this->is_publish;
    }

    public function setIsPublish(bool $is_publish): self
    {
        $this->is_publish = $is_publish;

        return $this;
    }

    /**
     * @return Collection|UrlApotheose[]
     */
    public function getUrlapotheose(): Collection
    {
        return $this->urlapotheose;
    }

    public function getUrlapotheoses(): array
    {
        $urlList=[];
        foreach ($this->getUrlapotheose() as $url) {
            $urlList[]=[
               'url' => $url->getUrl(),
               'id'=>$url->getId()
            ]
            ;
        }
        return $urlList;
    }

    public function addUrlapotheose(UrlApotheose $urlapotheose): self
    {
        if (!$this->urlapotheose->contains($urlapotheose)) {
            $this->urlapotheose[] = $urlapotheose;
            $urlapotheose->setApotheose($this);
        }

        return $this;
    }

    public function removeUrlapotheose(UrlApotheose $urlapotheose): self
    {
        if ($this->urlapotheose->removeElement($urlapotheose)) {
            // set the owning side to null (unless already changed)
            if ($urlapotheose->getApotheose() === $this) {
                $urlapotheose->setApotheose(null);
            }
        }

        return $this;
    }



}

src/Form/ApotheoseType.php
<?php

namespace App\Form;

use App\Entity\Apotheose;
use App\Entity\UrlApotheose;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApotheoseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'promo', TextType::class, [
                'attr'=> [
                    'placeholder'=> 'Nom de la promo',
                    'class'=>'form-control'
                ]
                ]
            )

            ->add(
                'description', TextareaType::class, [
                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]
                ]
            )
            ->add('is_publish')
            ->add(
                'urlapotheose', EntityType::class, [
                'label' => 'Quelle est l\'url lié a cette apothéose : ',
                'class' => UrlApotheose::class,
                'choice_label' => 'url',
                'multiple'=>true,
                'expanded'=>false,
                 ]
            ); 
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
            'data_class' => Apotheose::class,
            ]
        );
    }
}

src/Controller/ApotheoseController.php
<?php

namespace App\Controller;

use App\Entity\Apotheose;
use App\Form\ApotheoseType;
use App\Repository\ApotheoseRepository;
use App\Repository\UrlApotheoseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/apotheose")
 */
class ApotheoseController extends AbstractController
{
    /**
     * @Route("/", name="apotheose_index", methods={"GET"})
     */
    public function index(ApotheoseRepository $apotheoseRepository): Response
    {
        return $this->render(
            'apotheose/index.html.twig', [
            'apotheoses' => $apotheoseRepository->findAll(),
            ]
        );
    }

        /**
         * @Route("/new", name="apotheose_new", methods={"GET","POST"})
         */
    public function new(Request $request, UrlApotheoseRepository $UrlApoRepo): Response
    {
        $apotheose = new Apotheose();
        $form = $this->createForm(ApotheoseType::class, $apotheose);
        $form->handleRequest($request);
        dump($apotheose);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $data=$form->getData();
            $urls=$data->getUrlapotheose();
            dump($urls);
            $entityManager = $this->getDoctrine()->getManager();
            $promo=$data->getPromo();
            $description=$data->getDescription();
            $apotheose->setPromo($promo);
            $apotheose->setDescription($description);
            $entityManager->persist($apotheose);
            $urlapotheoses=[];
            foreach ($urls as $url) {
                   $urlid=$url->getid(); 
                   $url = $UrlApoRepo->find($urlid); 
                $url->setApotheose($apotheose);
                $entityManager->persist($url);
                $urlapotheoses[]=$url;
            }  
            $entityManager->flush();
        
            dump($urlapotheoses);

            return $this->redirectToRoute('apotheose_index', [], Response::HTTP_SEE_OTHER);  
        }  

        return $this->renderForm(
            'apotheose/new.html.twig', [
            'apotheose' => $apotheose,
            'form' => $form,
            ]
        );
    }

    /**
     * @Route("/{id}", name="apotheose_show", methods={"GET"})
     */
    public function show(Apotheose $apotheose, UrlApotheoseRepository $urlApoRepo): Response
    {
        $urls=$urlApoRepo->findByApotheose($apotheose);
        dump($urls);
        return $this->render(
            'apotheose/show.html.twig', [
            'apotheose' => $apotheose,
            'urllist'=>$urls,
            ]
        );
    }

    /**
     * @Route("/{id}/edit", name="apotheose_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Apotheose $apotheose,UrlApotheoseRepository $urlRepo, $id): Response
    {
        $form = $this->createForm(ApotheoseType::class, $apotheose);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data=$form->getData();
            $urls=$data->getUrlapotheose();
            dump($id);
            $entityManager = $this->getDoctrine()->getManager();
            $promo=$data->getPromo();
            $description=$data->getDescription();
            $apotheose->setPromo($promo);
            $apotheose->setDescription($description);
            $entityManager->persist($apotheose);
            $urlapotheoses=[];
            if (!empty($urls) ) {
                $urlRepoApo=$urlRepo->findByApotheose($id);
                //modification des champ de la table urlapothéose a null pour supprimer l'apothéose.
                $cleanUrlApo=[];
                foreach ($urlRepoApo as $url) {
                    $urlid=$url->getid(); 
                    $url = $urlRepo->find($urlid); 
                    $url->setApotheose(null);
                    $entityManager->persist($url);
                    $cleanUrlApo[]=$url;
                }
                $urlapotheoses=[];
                //Puis il pousse les modifications
                foreach ($urls as $url) {
                    $urlid=$url->getid(); 
                    $url = $urlRepo->find($urlid); 
                    $url->setApotheose($apotheose);
                    $entityManager->persist($url);
                    $urlapotheoses[]=$url;
                };  
            }
            //sinon il les pousse sans faire de modif
            foreach ($urls as $url) {
                $urlid=$url->getid(); 
                $url = $urlRepo->find($urlid); 
                $url->setApotheose($apotheose);
                $entityManager->persist($url);
                $urlapotheoses[]=$url;
            }  
            $entityManager->flush();
        
            dump($urlapotheoses);

            return $this->redirectToRoute('apotheose_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm(
            'apotheose/edit.html.twig', [
            'apotheose' => $apotheose,
            'form' => $form,
            ]
        );
    }

    /**
     * @Route("/{id}", name="apotheose_delete", methods={"POST"})
     */
    public function delete(Request $request, Apotheose $apotheose,UrlApotheoseRepository $urlRepo, $id): Response
    {
        if ($this->isCsrfTokenValid('delete'.$apotheose->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            //Recupération de l'id de l'apothéose
            $idApotheose=$apotheose->getId();
           
            // Recherche des url lier a cette apothéose
            $urls=$urlRepo->findByApotheose($idApotheose);
            //modification des champ de la table urlapothéose a null pour supprimer l'apothéose.
            $urlapotheoses=[];
            foreach ($urls as $url) {
                   $urlid=$url->getid(); 
                   $url = $urlRepo->find($urlid); 
                $url->setApotheose(null);
                $entityManager->persist($url);
                $urlapotheoses[]=$url;
            }  
            $entityManager->remove($apotheose);
            $entityManager->flush();
        }

        return $this->redirectToRoute('apotheose_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/apotheose/_delete_form.html.twig
<form method="post" action="{{ path('apotheose_delete', {'id': apotheose.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ apotheose.id) }}">
    <button class="btn">Delete</button>
</form>

templates/apotheose/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/apotheose/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Apotheose{% endblock %}

{% block body %}
    <h1>Edit Apotheose</h1>

    {{ include('apotheose/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('apotheose_index') }}">back to list</a>

    {{ include('apotheose/_delete_form.html.twig') }}
{% endblock %}

templates/apotheose/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Apotheose index{% endblock %}

{% block body %}
    <h1>Apotheose index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Promo</th>
                <th>Description</th>
                <th>CreatedAt</th>
                <th>Is_publish</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for apotheose in apotheoses %}
            <tr>
                <td>{{ apotheose.id }}</td>
                <td>{{ apotheose.promo }}</td>
                <td>{{ apotheose.description }}</td>
                <td>{{ apotheose.createdAt ? apotheose.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ apotheose.isPublish ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('apotheose_show', {'id': apotheose.id}) }}">show</a>
                    <a href="{{ path('apotheose_edit', {'id': apotheose.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('apotheose_new') }}">Create new Apothéose</a> 
     <a href="{{ path('url_apotheose_new') }}">Create new URl</a>
     <a href="{{ path('url_apotheose_index') }}">Index Url</a>
{% endblock %}

templates/apotheose/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Apotheose{% endblock %}

{% block body %}
    <h1>Create new Apotheose</h1>

    {{ include('apotheose/_form.html.twig') }}

    <a href="{{ path('apotheose_index') }}">back to list</a>
{% endblock %}

templates/apotheose/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Apotheose{% endblock %}

{% block body %}
    <h1>Apotheose</h1> 
    <table class="table">
        <tbody>
            <tr>
                <th class="w-25">Id</th>
                <td class="w-75">{{ apotheose.id }}</td>
            </tr>
            <tr>
                <th class="w-25">Promo</th>
                <td class="w-75">{{ apotheose.promo }}</td>
            </tr>
            <tr>
                <th class="w-25">Description</th>
                <td class="w-75">{{ apotheose.description }}</td>
            </tr>
            <tr>
                <th class="w-25">CreatedAt</th>
                <td class="w-75">{{ apotheose.createdAt ? apotheose.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th class="w-25">Is_publish</th>
                <td class="w-75">{{ apotheose.isPublish ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th class="w-25">liste des url </th>               
                <td class="w-75 videoapotheose"> {% for url in urllist %}
                <div>adresse:{{url.url}} </br>
                <iframe width=48% height=48% src={{url.url}} title="YouTube video player of Apotheose" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                 </div>
                {% endfor %}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('apotheose_index') }}">back to list</a>

    <a href="{{ path('apotheose_edit', {'id': apotheose.id}) }}">edit</a>

    {{ include('apotheose/_delete_form.html.twig') }}
{% endblock %}