src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Ignore;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $story;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_search_job;

    /**
     * @var                     array
     * @ORM\Column(type="json")
     * @Ignore()
     */
    private $roles = [];

    /**
     * @var                       string The hashed password
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\ManyToMany(targetEntity=Techno::class, mappedBy="user")
     */
    private $technos;

    /**
     * @ORM\ManyToMany(targetEntity=Contrat::class, mappedBy="user")
     */
    private $contrats;

    /**
     * @ORM\ManyToOne(targetEntity=Spe::class, inversedBy="Users")
     */
    private $spe;

    /**
     * @ORM\OneToMany(targetEntity=Team::class, mappedBy="user")
     */
    private $teams;

    public function __construct()
    {
        /* $this->roles = new ArrayCollection(); */
        $this->technos = new ArrayCollection();
        $this->contrats = new ArrayCollection();
        $this->teams = new ArrayCollection();
    }
    
    public function jsonSerialize(): array
    {
        return [
            'roles'=> $this->roles,
        ];
    }

    /* public function __tostring()
    {
        $this->id;
        $this->technos;
        $this->firstname;
        $this->lastname;
        $this->email;
        $this->story;
        $this->roles;
        $this->FLname= $this->lastname.'  '.$this->firstname;
        $this->teams;
        $this->spe;

        #  return $this->getFLname() ?:'';  
    }
    */
    public function getFLname(): ?string
    {
        $FLname= $this->lastname .' '. $this->firstname;
        return $FLname;
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getStory(): ?string
    {
        return $this->story;
    }

    public function setStory(?string $story): self
    {
        $this->story = $story;

        return $this;
    }

    public function getIsSearchJob(): ?bool
    {
        return $this->is_search_job;
    }

    public function setIsSearchJob(bool $is_search_job): self
    {
        $this->is_search_job = $is_search_job;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        /*     if (empty($roles)) {
            $roles[]='ROLE_USER';
        } ; */

        return array_unique($roles);
    }

  
    public function getRole(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
         //if (empty($roles)) {
          
        //} ;


        return array_unique($roles);
    }

    public function getRoles1(): ?array
    {
        $roles = $this->roles;

        return array($roles);
    }

    public function setRoles1(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function setRoles($roles): array
    {
        $role=[];
        $role[]=$roles;
        /*       foreach($roles as $role){
            return $role;
        } */
        return $role;

    }

    /**
     * @see UserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }


    /**
     * @return Collection|Techno[]
     */
    public function getTechnos(): Collection
    {
        return $this->technos;
    }

    public function getTechnoName(): ?string
    {
        return $this->technos->getName();
    }


    public function addTechno(Techno $techno): self
    {
        if (!$this->technos->contains($techno)) {
            $this->technos[] = $techno;
            $techno->addUser($this);
        }

        return $this;
    }

    public function getTechno(): array
    {
        $technoList=[];
        foreach ($this->getTechnos() as $techno) {
            $technoList[]=[
               'name' => $techno->getName(),
               'logo'=>$techno->getLogo(),
               'id'=>$techno->getId()
            ]
            ;
        }
        return $technoList;
    }

    public function removeTechno(Techno $techno): self
    {
        if ($this->technos->removeElement($techno)) {
            $techno->removeUser($this);
        }

        return $this;
    }




    /**
     * @return Collection|Contrat[]
     */
    public function getContrats(): Collection
    {
        return $this->contrats;
    }
    public function getContrat(): array
    {
        $contratList=[];
        foreach ($this->getContrats() as $contrat) {
            $contratList[]=[
               'name' => $contrat->getName(),
               'id'=>$contrat->getId()
            ]
            ;
        }
        return $contratList;
    }

    public function addContrat(Contrat $contrat): self
    {
        if (!$this->contrats->contains($contrat)) {
            $this->contrats[] = $contrat;
            $contrat->addUser($this);
        }

        return $this;
    }

    public function removeContrat(Contrat $contrat): self
    {
        if ($this->contrats->removeElement($contrat)) {
            $contrat->removeUser($this);
        }

        return $this;
    }

    // 
    // SPE ############
    // 



    public function getSpeList(): array
    {
        $speList=[];
        $speList[]=[
            'id'=> $this->spe->getId(),
            'name'=>$this->spe->getName()
        ];

        return $speList;
    }

    public function getSpe(): ?Spe
    {
        return $this->spe;
    }

    public function setSpe(?Spe $spe): self
    {
        $this->spe = $spe;

        return $this;
    }

    public function getSpeName(): ?Spe
    {
        return $this->spe->getName();
    }

    // 
    // Partie Login##
    // 

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }


    ///**
    // * @see UserInterface
    // */
    /*     public function getRoles1(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles1(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    } */


    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword1(): string
    {
        return $this->password;
    }

    public function setPassword1(string $password): self
    {
        $this->password = $password;

        return $this;
    } 

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Team[]
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function addTeam(Team $team): self
    {
        if (!$this->teams->contains($team)) {
            $this->teams[] = $team;
            $team->setUser($this);
        }

        return $this;
    }

    public function removeTeam(Team $team): self
    {
        if ($this->teams->removeElement($team)) {
            // set the owning side to null (unless already changed)
            if ($team->getUser() === $this) {
                $team->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Spe;
use App\Entity\Techno;
use App\Entity\Contrat;
use App\Repository\SpeRepository;
use App\Repository\TechnoRepository;
use App\Repository\ContratRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'firstname', TextType::class, [
                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]
                ]
            )
            ->add(
                'lastname', TextType::class, [
                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]
                ]
            )
            ->add(
                'email', EmailType::class, [
                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]
                ]
            )
            ->add(
                'story', TextareaType::class, [
                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]
                ]
            )
            ->add('is_search_job')

            ->add(
                'roles', ChoiceType::class, [
                'required' => true,
     
                'choices'=>[
                    'select'=>null,
                    'Administrateur'=> 'ROLE_ADMIN',
                    'Utilisateur'=>'ROLE_USER',
                ],
                'expanded' => false,
                'multiple' => false,
                'label' => 'Rôles' 

                ]
            )
/*             ->add(
                'password', PasswordType::class, [

                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]

                  ]
            )   */
            ->add(
                'picture', UrlType::class, [

                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]

                ]
            )
            ->add(
                'spe', EntityType::class,

                [
                'label' => 'Quel est la spe',
                'class' => Spe::class,
                'choice_label' => 'name',
                'attr'=> [
                    'placeholder'=> 'Description de l\'Apotheose',
                    'class'=>'form-control'
                ]
                ],
            )
            ->add(
                'technos', EntityType::class, [
                'label' => 'Quelle est la techno que l\'utilisateur connait :',
                'class' => Techno::class,
                'choice_label' => 'name',
                'multiple'=>true,
                'expanded'=>true,
                ]
            )
            ->add(
                'contrats', EntityType::class, [
                'label' => 'Quelle est le type de contrat que l\'utilisateur souhaite :',
                'class' => Contrat::class,
                'choice_label' => 'name',
                'multiple'=>true,
                'expanded'=>true,
                ]
            );
    }


    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
            'data_class' => User::class,
            ]
        );
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_filter.html.twig
{{form_start(form)}}
    <button type="submit" class="btn btn-primary w-25">Search User</button>
{{form_end(form)}}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}
    <h1>Edit User</h1>


    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_index') }}">back to list</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

<div>
{% include 'user/_filter.html.twig' with {form: form} only %}
</div>


  <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Email</th>
                <th>Story</th>
                <th>Is_search_job</th>
                <th>Roles</th>
                <th>Picture</th>
                {%if isSearchUser == 1%}
                {%else%}
                <th>Spe</th>
                {%endif%}
                <th>actions</th>

            </tr>
        </thead>
        <tbody>

        {% for user in users |slice(numberusernim, 10) %}

            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.story }}</td>
                <td> {{ user.is_search_job ? 'Yes' : 'No' }}</td>
              
                {% if isSearchUser == 1 %}
                <td> 
                    {%if user.roles == []%}
                          Pas de role
                    {% else %}
                        {%for role in user.roles%}
                         {{role}} 
                        {%endfor%}
                    {% endif %}
                </td>
                {% else %}
                <td>  {{ user.roles  }}              
                {%endif%}</td>   
                <td>{{ user.picture }}</br>
                <img class="w-25" src="{{user.picture}}" alt="Logo of user">
                </td>
                 {%if isSearchUser == 1%}
                 {%else%}
                <td> {{user.speName}} </td>
                {%endif%}
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                    <a href="{{path('user_delete', {'id':user.id}) }}">Delete</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% set i=1 %}
    {%for i in i..countresult%}
    {% if i==1 %}

        <a href="{{path('user_index')}}?page={{i}}"> Start</a>
    {%elseif i==countresult%}
            <a href="{{path('user_index')}}?page={{i}}">End</a>
    {% else %}
    <a href="{{path('user_index')}}?page={{i}}"> page:{{i}}</a>
    {%endif%}
    {%endfor%}</br>
    <a class="btn btn-primary" href="{{ path('user_new') }}" role="button">Create new</a>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>
   
{{ include('user/_form.html.twig') }}
    

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
    <h1>User</h1>

    <table class="table">
    

        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Story</th>
                <td>{{ user.story }}</td>
            </tr>
            <tr>
                <th>Is_search_job</th>
                <td>{{ user.isSearchJob ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>

            <tr>
                <th>Picture</th>
                <td>{{ user.picture }}</td>
            </tr>
                        <tr>
                <th>Spe</th>
                <td>
                   {% for spe1 in spe %}
               {{spe1.name}} 
                 {% endfor %} </td>
              
              
            </tr>
            <tr>
                <th>Technos</th>
                <td>
                {% for techno in technos %}
                {{techno.name}} 
                {% endfor %}</td>
            </tr>
            <tr>
                <th>contrats</th>
                <td>
                {% for contrat in contrats %}
                {{contrat.name}} 
                {% endfor %}</td>
            </tr>

        </tbody>
    </table>

    <a href="{{ path('user_index') }}">back to list</a>

    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/test.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}